### Get all courses
GET http://localhost:4000/api/courses

### Get a single course
GET http://localhost:4000/api/courses/6935831a3e4de109b63df5f2


### Add a course
POST http://localhost:4000/api/courses
Content-Type: application/json

  {
    "title": "React Basics",
  "duration": "3 months",
  "fee": 150,
  "instructor": {
    "name": "John Doe",
    "contactEmail": "john@example.com",
    "contactPhone": "1234567890"
  }
  }

###Delete a course


DELETE  http://localhost:4000/api/courses/6935831a3e4de109b63df5f2


###Update a course
PUT http://localhost:4000/api/courses/6935942842431b6a233f1883
Content-Type: application/json

  {
    "title": "ROOOOOO"}


### Signup a new user

POST http://localhost:4000/api/users/signup
Content-Type: application/json

{
"username": "johndoe",
"password": "123456",
"name": "John Doe",
"gender": "Male",
"date_of_birth": "1990-01-01",
"address": "123 Street, City",
"occupation": "Engineer"
}

### Login user

POST http://localhost:4000/api/users/login
Content-Type: application/json

{
"username": "johndoe",
"password": "123456"
}


